version: "3"

services:
  db:
    image: mysql
    environment:
      - MYSQL_HOST="localhost"
      - MYSQL_USER="root"
      - MYSQL_PASSWORD=""
      - MYSQL_DB="web_tech_final_project"
    volumes:
      - type: bind
        source: /mnt/staging_mysql
        target: /opt/mysql/data</i>
    ports:
      - "32000:3306"

  web:
    build: ./app
    command: python app.py # may need to be changed to 'flask run'
    ports:
      - "5000:5000"
    depends_on:
      - db
